### ISSUE TITLE
Question: How to modify to handle multiple file uploads?

### ISSUE THREAD

**Issue by shaunflagg** [jbesw/askjames-s3uploader#15]
How would you modify this code to handle multiple file uploads?

Would you have to do something like this in the s3uploader component
 
```
export default {
  props: ['files'],
  data () {
    return {
      file: ''
    }
  },
```

**Comment by jbesw** [comment]
Sorry for the delay in responding - I didn't receive a notification on this issue. I would recommend either (1) zip up the contents on the frontend and then unzip on the backend, uploading as a single file or (2) making multiple requests to S3 for several uploads in parallel. In JavaScript, you can parallelize these requests and uploads instead of making sequential calls.
